services:
  mysql:
    image: mysql:8.0
    container_name: contact-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact_management
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: